#!/bin/bash
declare -a amounts
export total=$1
for amount in $(hledger reg checking -P amt:"<$total" --invert -O csv | awk -F, '{gsub(/"/, ""); gsub(/ USD/, ""); if (NR!=1) {print $(NF-1)}}')
do
    amounts+=("$amount")
done
export trans_count=${#amounts[@]}
until [ ${#ones} -eq "$trans_count" ];do ones+="1"; done
function get_pattern()
    {
    declare -a amounts
    for i in "$@"
    do
        if [ "$count" ]
        then
            amounts+=("$i")
        fi
        count=1
    done
    binary=$(echo "obase=2;$1" | bc)
    if [ "$trans_count" -ne ${#binary} ]
    then
        until [ ${#zeros} -eq $((trans_count-${#binary})) ];do zeros+="0";done
        form_binary="$zeros""$binary"
    else
        form_binary="$binary"
    fi   
    for ((n=0; n<=trans_count; n++ ))
    do
        if [ "${form_binary:n:1}" ==  1 ]
        then
            price="${amounts[$n]}"
            if [ -z "$prices" ]
            then
                sum="$price"
            else
                sum=$(echo "$sum" + "$price" | bc -l)
            fi
            prices+="${amounts[$n]} "
        fi
    done
    if [ "$sum" == "$total" ] 
    then
        echo "Possibly Cleared:"
        echo "-----------------"
        for price in $prices
        do
            hledger reg checking -P amt:"$price"
        done
    fi
    unset sum
    unset prices
    unset zeros
    }
export -f get_pattern
seq "$((2#$ones))" | parallel get_pattern {} "${amounts[*]}" 
